version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-28-alpha
    working_directory: ~/work
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
      TERM: dumb

commands:
  store-artifacts:
    description: "It stores Lint & Test artifacts"
    parameters:
      artifact-path:
        type: string
    steps:
      - store_artifacts:
          path: <<parameters.artifact-path>>

jobs:
  build_and_test:
    executor: android-executor
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Assemble apk for application and tests
          command: ./gradlew check :app:assembleDebug :app:assembleDebugAndroidTest
      - run:
          name: Gather Lint results
          command: scripts/copy_lint_results.sh
      - store-artifacts:
          artifact-path: ci_results/lint
      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build

  deploy_to_deploygate:
    executor: android-executor
    steps:
      - checkout
      - attach_workspace:
          at: ~/work
      - run:
          name: Deploy to DeployGate
          command: curl -F "file=@app/build/outputs/apk/debug/app-debug.apk" -F "token=$DEPLOYGATE_API_KEY" https://deploygate.com/api/users/ArnaudPiroelle/apps

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy_to_deploygate:
          requires:
            - build_and_test
          filters:
            tags:
              ignore: /.*/
            branches:
              only: develop